### ISSUE TITLE
Use of our testing capacity data

### ISSUE THREAD

**Issue by hammer** [AaronWard/covid-19-analysis#10]
Hey we have been trying to track state-level reports of tests performed at https://twitter.com/covid19tracking. We have a Slack workspace where some people are discussing how to incorporate this data into visualizations. Would y'all like an invite to the Slack workspace?

**Comment by AaronWard** [comment]
@hammer Sure, i dont have a slack account but message me the invite on my linkedin (in the README) and i’ll join once i have made one 

Thank you😊
