### ISSUE TITLE
RFE: restrict to country

### ISSUE THREAD

**Issue by btong** [AaronWard/covid-19-analysis#11]
Could there be an option to restrict the charts to a given country?

**Comment by peteblois** [comment]
In https://github.com/AaronWard/covid-19-analysis/issues/8 I included a link to the code as a notebook.

Here's that notebook tweaked to add a filter by country:
https://colab.research.google.com/gist/peteblois/b02efa5a647221e8e628686ee485f4b6/copy-of-covid-19-analysis.ipynb#scrollTo=PsALnEdTb5pF

**Comment by AaronWard** [comment]
@btong @peteblois I will add this as a feature, so that you can run a command like

```
covidify run --output=<some folder> --country="Mainland China" 
```

and it will only output results for that country.

**Comment by AaronWard** [comment]
https://github.com/AaronWard/covid-19-analysis/projects/1#card-34349580

**Comment by AaronWard** [comment]
@peteblois @btong 

Feature is now available on the new release, enjoy 👍

**Comment by btong** [comment]
Brilliant! Works great! Thank you!
