### ISSUE TITLE
log-plots per country

### ISSUE THREAD

**Issue by fabiansvara** [AaronWard/covid-19-analysis#13]
A great way to compare the spread of Covid19 between countries at different stages of the outbreak is to look at the data in a log plot, since it makes any deviations from constant exponential growth really obvious.

See this here for an example of what I mean:

https://twitter.com/MarkJHandley/status/1237144386569416712/photo/1

What can also be helpful is to normalize the number of people infected to the population of the country, which makes it more intuitively clear how hard a country is hit.

The plot in the link above is great because it shifts the countries around in time to show how predictable the growth is, but that isn't absolutely necessary.

It would be great if your tool allowed making similar plots, for a user-defined selection of countries.

Thanks for your work!

**Comment by AaronWard** [comment]
@fabiansvara sounds like a good idea to incorporate this, someone hackernews said this too so i will look into it. Thank you

**Comment by AaronWard** [comment]
@fabiansvara Log plot in the newest release
