### ISSUE TITLE
Data Missing When Parsed

### ISSUE THREAD

**Issue by Konsole512** [AaronWard/covid-19-analysis#19]
Seems to be a bug in how it's parsing the csv pulled from the repo. As a test we will use "US" and "Texas"

covidify run --country="US"

Located in the "/tmp/corona/COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/" folder, the csv reports show correct metrics for "Texas" which at this moment is "43" which can be varified from "https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports"

When the CSV is parsed for metrics the resulting "agg_data_2020-03-14.csv" results in a status of "27" listed for Texas which obviously suggests some discrepancy.

**Comment by AaronWard** [comment]
@Konsole512 Hey

i wrote about the problems in the readme. I am currently trying to fix the discrepancies with the JHU data and i will release the newest version as soon as possible

Thanks for raising the concern!
