### ISSUE TITLE
Upload to PyPI?

### ISSUE THREAD

**Issue by brainwane** [AaronWard/covid-19-analysis#2]
Hi! In case you haven't considered it yet, [here are instructions for packaging your repo and uploading to the Python Package Index](https://packaging.python.org/tutorials/distributing-packages/) so people can `pip install` it without the `git clone` step.

**Comment by AaronWard** [comment]
Thanks for the suggestion, i will put it on the backlog for things to do. 👌🏼

**Comment by AaronWard** [comment]
@brainwane Nearly done, just need to make a few changes then i will be uploading it to the package index

**Comment by AaronWard** [comment]
`pip install covidify`

**Comment by brainwane** [comment]
Thank you, hope people find the easier installation useful, and hope my link was helpful!
