### ISSUE TITLE
program files windows error

### ISSUE THREAD

**Issue by deciacco** [AaronWard/covid-19-analysis#7]
Hi... thought this was really cool and i wanted to try it on my Windows machine. (This could very well be an issue with my install, but...)

Windows 10, Python 3.8.

Installed with `pip install covidify`. Everything went well.

When I run `covidify run` I get this:
```
PS C:\> covidify run
     MESSAGE: [1;31m No output directory given, defaulting to /Users/<username>/Desktop/covidify-output/ [0;0m
     MESSAGE: [1;31m No source given, defaulting to John Hopkin CSSE github repo [0;0m
'c:\program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by AaronWard** [comment]
@deciacco 
```
- MESSAGE: �[1;31m No output directory given, defaulting to /Users/<username>/Desktop/covidify-output/ �[0;0m
- MESSAGE: �[1;31m No source given, defaulting to John Hopkin CSSE github repo �[0;0m
```

These two aren't errors, they are just messages to tell you the default options are set.

As for the `'c:\program'` error, i have never seen this before. Are you using a conda environment or are you using a vanilla python installation?

**Comment by deciacco** [comment]
thanks for your reply... i'd say it's vanilla installation. simply downloaded 64bit installer from python.org... installed for all users to "c:\program files\python38\" as windows likes, etc. it has something to do with the path and not liking the space between program files.

**Comment by AaronWard** [comment]
@deciacco I'd advise to use conda, it will make your life so much easier in the furure when running into these installations errors that aren't always that obvious whats wrong. You can install from [here](https://www.anaconda.com/distribution/) 

make a conda environment using the `conda create` command. When you activate the environment and pip install the covidify package, all the dependencies will be installed to that conda environment, and can be seen by your python installation

**Comment by deciacco** [comment]
@AaronWard thanks for the tip... i'll give it a try!
